<?php

namespace AppBundle\Repository;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * ContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentRepository extends \Doctrine\ORM\EntityRepository
{
    public function save($entity)
    {
        $this->_em->persist($entity);
        $this->_em->flush();

        return true;
    }

    /**
     * @param string $key
     *
     * @return ArrayCollection
     */
    public function findByKeyword($key)
    {
        $qb = $this->createQueryBuilder("e");

        $qb->select('e')
//            ->where('e.status = 1')
            ->where('e.title LIKE :key OR e.description LIKE :key')
            ->andWhere('e.parent IS NULL')
            ->setParameter('key', '%' . $key . '%');
        ;

        $result = $qb->getQuery()->getResult();

        return $result;
    }
}
