<?php

namespace AppBundle\Repository;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param string $key
     *
     * @return ArrayCollection
     */
    public function findByKeyword($key)
    {
        $qb = $this->createQueryBuilder("e");

        $qb->select('e')
            ->where('e.enabled = 1')
            ->andWhere('e.username LIKE :key')
            ->setParameter('key', '%' . $key . '%');
        ;

        $result = $qb->getQuery()->getResult();

        return $result;
    }
}
