# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:

services:
    twig_asset_version_extension:
        class: AppBundle\Twig\AssetVersionExtension
        arguments: ["%kernel.root_dir%"]
        tags:
            - { name: twig.extension }
    app.form.profile:
        class: AppBundle\Form\ProfileFormType
    app.password_resetting:
        class: AppBundle\Listener\ChangePasswordListener
        arguments: [ '@router' ]
        tags:
            - { name: kernel.event_subscriber }
    app.user.login:
        class: AppBundle\Listener\LoginListener
        tags:
            - { name: kernel.event_subscriber }